name: flutter_soloud_example
description: "flutter_soloud example."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  
  #https://pub.dev/packages/file_picker
  file_picker: ^8.1.2

  flutter:
    sdk: flutter

  flutter_soloud: ^2.1.0
    
  #https://pub.dev/packages/logging
  logging: ^1.2.0

  #https://pub.dev/packages/path_provider
  path_provider: ^2.1.4

  #https://pub.dev/packages/star_menu
  star_menu: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/

  shaders:
    - assets/shaders/test1.frag
    - assets/shaders/test2.frag
    - assets/shaders/test3.frag
    - assets/shaders/test4.frag
    - assets/shaders/test5.frag
    - assets/shaders/test6.frag
    - assets/shaders/test7.frag
    - assets/shaders/test8.frag
    - assets/shaders/test9.frag